import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar'
import Filter from '@/components/filter'
const nunito = Nunito({ 
  subsets: ['latin'],
  weight: ['300', '600', '800']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Navbar />
        {/* <Filter /> */}
        {children}
      </body>
    </html>
  )
}
